### ISSUE TITLE
Suggestion - Remap Inc/Dec Speed

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#11]
Problem:
Uncomfortable to use current G/H mapping.

Suggested Solution / Addition:
Please change mapping.

How should solution be implemented?:
Please change mapping to R/F (R - faster, F - slower)

Additional Details (If needed):
<--->

**Comment by cavecomputing** [comment]
I think it would be better to just make it re mappable by the user via a UI since other mods might map to F or R. As far as putting a tool in your offhand, isn't F already used for that?

Alternatively, Tapping shift could make the horse faster and Control could make it slower. Feels more natural I think, at least as a default, and then re mappable by the user.

**Comment by MagnusHJensen** [comment]
> I think it would be better to just make it re mappable by the user via a UI since other mods might map to F or R. As far as putting a tool in your offhand, isn't F already used for that?
> 
> Alternatively, Tapping shift could make the horse faster and Control could make it slower. Feels more natural I think, at least as a default, and then re mappable by the user. Unless shift and control are already used. I don't ride horses enough to tell.

Shift is used for dismounting.

The keys were selected by no standard, the keys are remappable in the options menu.

**Comment by cavecomputing** [comment]
Ahhh gotchya. My minecraft inexperience is showing :) 

Since we can already remap the keys should we just add an entry in the wiki on how to remap the keys and close this?

**Comment by MagnusHJensen** [comment]
I'll personally say, this is a closed case for now, until we have enough people complaining about the default keybinds, I won't do much about it.
